!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: Pixel 5
  udid: emulator-5554
  app: /Users/caraerna/projects/apk/sample-apk.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
